/** 14 Kerala districts. Each loads as its own map. */

export const DISTRICTS = [
  {
    id: "tvm", name: "Thiruvananthapuram", kind: "coastal", seed: 0.7,
    start: { x: -72, z: 10 },
    places: [
      { id: "kovalam", name: "Kovalam", kind: "beach", x: -110, z: -48 },
      { id: "shanghu", name: "Shanghumukham", kind: "beach", x: -108, z: 36 },
      { id: "padmanabha", name: "Padmanabhaswamy", kind: "temple", x: 8, z: 22 },
      { id: "kanaka", name: "Kanakakkunnu", kind: "fort", x: 28, z: 8 },
      { id: "vizhinjam", name: "Vizhinjam", kind: "jetty", x: -86, z: -88 },
      { id: "poovar", name: "Poovar", kind: "houseboat", x: -58, z: -120 },
      { id: "akkulam", name: "Akkulam", kind: "lake", x: 36, z: 70 },
      { id: "ponmudi", name: "Ponmudi", kind: "peak", x: 124, z: -40 },
      { id: "napier", name: "Museum Lane", kind: "market", x: -6, z: 6 },
      { id: "pond", name: "Kulam", kind: "pond", x: 18, z: -16 },
      { id: "chaya", name: "Chaya Kada", kind: "chaya", x: -16, z: 8 },
      { id: "thattu", name: "Thattukada", kind: "thattukada", x: -24, z: -10 },
      { id: "hotel", name: "Lodge", kind: "hotel", x: 4, z: -8 },
    ],
  },
  {
    id: "kollam", name: "Kollam", kind: "backwater", seed: 1.4,
    start: { x: -64, z: 6 },
    places: [
      { id: "ashtamudi", name: "Ashtamudi", kind: "houseboat", x: -56, z: -36 },
      { id: "kollambeach", name: "Kollam Beach", kind: "beach", x: -108, z: 20 },
      { id: "thangassery", name: "Thangassery", kind: "lighthouse", x: -92, z: 58 },
      { id: "jatayu", name: "Jatayu", kind: "peak", x: 118, z: -28 },
      { id: "thenmala", name: "Thenmala", kind: "forest", x: 96, z: 80 },
      { id: "munroe", name: "Munroe Island", kind: "houseboat", x: -48, z: -90 },
      { id: "thankasseri", name: "Harbour", kind: "jetty", x: -78, z: 8 },
      { id: "pond", name: "Kulam", kind: "pond", x: 12, z: 4 },
      { id: "chaya", name: "Chaya Kada", kind: "chaya", x: -10, z: 12 },
      { id: "thattu", name: "Thattukada", kind: "thattukada", x: -18, z: -6 },
      { id: "hotel", name: "Lodge", kind: "hotel", x: 8, z: 22 },
    ],
  },
  {
    id: "pta", name: "Pathanamthitta", kind: "midland", seed: 2.1,
    start: { x: 8, z: 4 },
    places: [
      { id: "sabarimala", name: "Sabarimala", kind: "temple", x: 42, z: 110 },
      { id: "aranmula", name: "Aranmula", kind: "temple", x: -18, z: -36 },
      { id: "gavi", name: "Gavi", kind: "forest", x: 108, z: 48 },
      { id: "konni", name: "Konni", kind: "forest", x: 70, z: -20 },
      { id: "kakki", name: "Kakki", kind: "lake", x: 90, z: -80 },
      { id: "paddy", name: "Paddy", kind: "paddy", x: -8, z: -70 },
      { id: "pond", name: "Kulam", kind: "pond", x: 16, z: 18 },
      { id: "chaya", name: "Chaya Kada", kind: "chaya", x: -4, z: 10 },
      { id: "thattu", name: "Thattukada", kind: "thattukada", x: 6, z: -12 },
      { id: "hotel", name: "Lodge", kind: "hotel", x: 22, z: 4 },
    ],
  },
  {
    id: "alpy", name: "Alappuzha", kind: "backwater", seed: 2.8,
    start: { x: -70, z: 8 },
    places: [
      { id: "alpybeach", name: "Alappuzha Beach", kind: "beach", x: -110, z: -20 },
      { id: "punnamada", name: "Punnamada", kind: "houseboat", x: -52, z: -40 },
      { id: "marari", name: "Marari", kind: "beach", x: -108, z: 70 },
      { id: "pathiramanal", name: "Pathiramanal", kind: "lake", x: -36, z: -88 },
      { id: "ambalapuzha", name: "Ambalapuzha", kind: "temple", x: 28, z: -24 },
      { id: "krishna", name: "Krishnapuram", kind: "fort", x: 48, z: 36 },
      { id: "jetty", name: "Boat Jetty", kind: "jetty", x: -78, z: 12 },
      { id: "pond", name: "Kulam", kind: "pond", x: 6, z: 8 },
      { id: "chaya", name: "Chaya Kada", kind: "chaya", x: -14, z: 6 },
      { id: "thattu", name: "Thattukada", kind: "thattukada", x: -22, z: -8 },
      { id: "hotel", name: "Lodge", kind: "hotel", x: 2, z: 20 },
    ],
  },
  {
    id: "ktm", name: "Kottayam", kind: "backwater", seed: 3.3,
    start: { x: -20, z: 6 },
    places: [
      { id: "kumarakom", name: "Kumarakom", kind: "houseboat", x: -62, z: -28 },
      { id: "illickal", name: "Illickal Kallu", kind: "peak", x: 122, z: 36 },
      { id: "ettumanoor", name: "Ettumanoor", kind: "temple", x: 18, z: 48 },
      { id: "pala", name: "Pala", kind: "church", x: 40, z: -40 },
      { id: "vagamonktm", name: "Vagamon road", kind: "peak", x: 108, z: -70 },
      { id: "paddy", name: "Paddy", kind: "paddy", x: 8, z: -88 },
      { id: "pond", name: "Kulam", kind: "pond", x: 4, z: 12 },
      { id: "chaya", name: "Chaya Kada", kind: "chaya", x: -8, z: 4 },
      { id: "thattu", name: "Thattukada", kind: "thattukada", x: -16, z: -10 },
      { id: "hotel", name: "Lodge", kind: "hotel", x: 12, z: 22 },
    ],
  },
  {
    id: "idk", name: "Idukki", kind: "highland", seed: 4.0,
    start: { x: 24, z: 0 },
    places: [
      { id: "munnar", name: "Munnar", kind: "tea", x: 88, z: -36 },
      { id: "eravikulam", name: "Eravikulam", kind: "peak", x: 128, z: 18 },
      { id: "mattupetty", name: "Mattupetty", kind: "lake", x: 70, z: 48 },
      { id: "thekkady", name: "Thekkady", kind: "forest", x: 40, z: 120 },
      { id: "periyar", name: "Periyar", kind: "lake", x: 16, z: 100 },
      { id: "idukkidam", name: "Idukki Dam", kind: "dam", x: -10, z: -20 },
      { id: "ramakkal", name: "Ramakkalmedu", kind: "peak", x: 110, z: -90 },
      { id: "pond", name: "Estate pond", kind: "pond", x: 36, z: -8 },
      { id: "chaya", name: "Chaya Kada", kind: "chaya", x: 18, z: 8 },
      { id: "thattu", name: "Thattukada", kind: "thattukada", x: 8, z: -6 },
      { id: "hotel", name: "Lodge", kind: "hotel", x: 32, z: 16 },
    ],
  },
  {
    id: "ekm", name: "Ernakulam", kind: "coastal", seed: 0.2,
    start: { x: -74, z: 12 },
    places: [
      { id: "fortkochi", name: "Fort Kochi", kind: "fort", x: -88, z: 24 },
      { id: "nets", name: "Chinese Nets", kind: "nets", x: -96, z: 42 },
      { id: "marine", name: "Marine Drive", kind: "jetty", x: -78, z: 8 },
      { id: "mattancherry", name: "Mattancherry", kind: "market", x: -40, z: 36 },
      { id: "cherai", name: "Cherai", kind: "beach", x: -110, z: 90 },
      { id: "hillpalace", name: "Hill Palace", kind: "fort", x: 48, z: -20 },
      { id: "bolgatty", name: "Bolgatty", kind: "hotel", x: -54, z: -36 },
      { id: "mangalavanam", name: "Mangalavanam", kind: "forest", x: 20, z: 70 },
      { id: "jewtown", name: "Jew Town", kind: "market", x: -28, z: 18 },
      { id: "pond", name: "Kulam", kind: "pond", x: 10, z: -8 },
      { id: "chaya", name: "Chaya Kada", kind: "chaya", x: -12, z: 6 },
      { id: "thattu", name: "Thattukada", kind: "thattukada", x: -20, z: -12 },
    ],
  },
  {
    id: "tsr", name: "Thrissur", kind: "midland", seed: 5.1,
    start: { x: 4, z: 8 },
    places: [
      { id: "vadakku", name: "Vadakkunnathan", kind: "temple", x: 12, z: 20 },
      { id: "guruvayur", name: "Guruvayur", kind: "temple", x: -36, z: 48 },
      { id: "peechi", name: "Peechi", kind: "lake", x: 88, z: 16 },
      { id: "chavakkad", name: "Chavakkad", kind: "beach", x: -108, z: 40 },
      { id: "vilangan", name: "Vilangankunnu", kind: "peak", x: 70, z: -50 },
      { id: "kalamandalam", name: "Kalamandalam", kind: "temple", x: 36, z: -80 },
      { id: "pond", name: "Kulam", kind: "pond", x: 22, z: -6 },
      { id: "chaya", name: "Chaya Kada", kind: "chaya", x: -8, z: 6 },
      { id: "thattu", name: "Thattukada", kind: "thattukada", x: -16, z: -10 },
      { id: "hotel", name: "Lodge", kind: "hotel", x: 8, z: -18 },
    ],
  },
  {
    id: "pkd", name: "Palakkad", kind: "midland", seed: 5.8,
    start: { x: 6, z: 0 },
    places: [
      { id: "pkdfort", name: "Palakkad Fort", kind: "fort", x: -8, z: 16 },
      { id: "malampuzha", name: "Malampuzha", kind: "lake", x: 48, z: 40 },
      { id: "silent", name: "Silent Valley", kind: "forest", x: 100, z: 90 },
      { id: "nelliyampathy", name: "Nelliyampathy", kind: "tea", x: 118, z: -40 },
      { id: "kalpathy", name: "Kalpathy", kind: "temple", x: 16, z: -28 },
      { id: "parambi", name: "Parambikulam", kind: "forest", x: 80, z: -90 },
      { id: "paddy", name: "Palakkad Gap", kind: "paddy", x: -20, z: -70 },
      { id: "pond", name: "Kulam", kind: "pond", x: 20, z: 8 },
      { id: "chaya", name: "Chaya Kada", kind: "chaya", x: -4, z: 4 },
      { id: "thattu", name: "Thattukada", kind: "thattukada", x: 10, z: -12 },
      { id: "hotel", name: "Lodge", kind: "hotel", x: 28, z: 18 },
    ],
  },
  {
    id: "mlp", name: "Malappuram", kind: "coastal", seed: 6.4,
    start: { x: -20, z: 6 },
    places: [
      { id: "ponnani", name: "Ponnani", kind: "beach", x: -108, z: -20 },
      { id: "ponnanimosque", name: "Ponnani Juma", kind: "mosque", x: -86, z: -8 },
      { id: "kottakkal", name: "Kottakkal", kind: "temple", x: 28, z: 24 },
      { id: "nilambur", name: "Nilambur Teak", kind: "forest", x: 108, z: 70 },
      { id: "tirur", name: "Tirur", kind: "paddy", x: -8, z: -70 },
      { id: "kottakkunnu", name: "Kottakkunnu", kind: "peak", x: 48, z: 8 },
      { id: "pond", name: "Kulam", kind: "pond", x: 8, z: 10 },
      { id: "chaya", name: "Chaya Kada", kind: "chaya", x: -10, z: 4 },
      { id: "thattu", name: "Thattukada", kind: "thattukada", x: -18, z: -8 },
      { id: "hotel", name: "Lodge", kind: "hotel", x: 4, z: 20 },
    ],
  },
  {
    id: "kkd", name: "Kozhikode", kind: "coastal", seed: 7.0,
    start: { x: -72, z: 8 },
    places: [
      { id: "kkdbeach", name: "Kozhikode Beach", kind: "beach", x: -110, z: -8 },
      { id: "kappad", name: "Kappad", kind: "beach", x: -108, z: 70 },
      { id: "mananchira", name: "Mananchira", kind: "pond", x: -8, z: 12 },
      { id: "smstreet", name: "SM Street", kind: "market", x: -16, z: 4 },
      { id: "beypore", name: "Beypore", kind: "jetty", x: -88, z: -70 },
      { id: "sarovaram", name: "Sarovaram", kind: "lake", x: 36, z: 48 },
      { id: "mishkal", name: "Mishkal Mosque", kind: "mosque", x: -40, z: 28 },
      { id: "chaya", name: "Chaya Kada", kind: "chaya", x: -24, z: 8 },
      { id: "thattu", name: "Thattukada", kind: "thattukada", x: -28, z: -6 },
      { id: "hotel", name: "Lodge", kind: "hotel", x: 6, z: 18 },
    ],
  },
  {
    id: "wyd", name: "Wayanad", kind: "highland", seed: 7.7,
    start: { x: 18, z: 4 },
    places: [
      { id: "edakkal", name: "Edakkal", kind: "cave", x: 96, z: -28 },
      { id: "banasura", name: "Banasura", kind: "dam", x: 40, z: 48 },
      { id: "chembra", name: "Chembra", kind: "peak", x: 124, z: 20 },
      { id: "pookode", name: "Pookode", kind: "lake", x: -8, z: -20 },
      { id: "kuruva", name: "Kuruva", kind: "forest", x: 20, z: 110 },
      { id: "tholpetty", name: "Tholpetty", kind: "forest", x: 80, z: 100 },
      { id: "pond", name: "Pookode edge", kind: "pond", x: 6, z: -12 },
      { id: "chaya", name: "Chaya Kada", kind: "chaya", x: 12, z: 10 },
      { id: "thattu", name: "Thattukada", kind: "thattukada", x: 4, z: -4 },
      { id: "hotel", name: "Lodge", kind: "hotel", x: 28, z: 16 },
    ],
  },
  {
    id: "knr", name: "Kannur", kind: "coastal", seed: 8.3,
    start: { x: -74, z: 8 },
    places: [
      { id: "payyambalam", name: "Payyambalam", kind: "beach", x: -110, z: -28 },
      { id: "angelo", name: "St. Angelo Fort", kind: "fort", x: -90, z: 22 },
      { id: "muzhappilangad", name: "Muzhappilangad", kind: "drivein", x: -112, z: 64 },
      { id: "thalassery", name: "Thalassery Fort", kind: "fort", x: -48, z: -88 },
      { id: "parassini", name: "Parassinikadavu", kind: "temple", x: 36, z: 52 },
      { id: "paithal", name: "Paithalmala", kind: "peak", x: 120, z: 16 },
      { id: "ezhimala", name: "Ezhimala", kind: "peak", x: 88, z: 110 },
      { id: "theyyam", name: "Theyyam Kavu", kind: "temple", x: 18, z: 96 },
      { id: "pond", name: "Kulam", kind: "pond", x: 8, z: -10 },
      { id: "chaya", name: "Chaya Kada", kind: "chaya", x: -14, z: 6 },
      { id: "thattu", name: "Thattukada", kind: "thattukada", x: -22, z: -8 },
      { id: "hotel", name: "Lodge", kind: "hotel", x: 2, z: 18 },
    ],
  },
  {
    id: "ksd", name: "Kasaragod", kind: "coastal", seed: 9.1,
    start: { x: -70, z: 6 },
    places: [
      { id: "bekal", name: "Bekal Fort", kind: "fort", x: -92, z: -20 },
      { id: "pallikere", name: "Pallikere", kind: "beach", x: -110, z: -36 },
      { id: "kappil", name: "Kappil Beach", kind: "beach", x: -108, z: 70 },
      { id: "chandragiri", name: "Chandragiri", kind: "fort", x: -40, z: 36 },
      { id: "ananthapura", name: "Ananthapura", kind: "temple", x: 28, z: 24 },
      { id: "ranipuram", name: "Ranipuram", kind: "peak", x: 122, z: 40 },
      { id: "valiyaparamba", name: "Valiyaparamba", kind: "houseboat", x: -56, z: -90 },
      { id: "pond", name: "Kulam", kind: "pond", x: 10, z: -8 },
      { id: "chaya", name: "Chaya Kada", kind: "chaya", x: -12, z: 8 },
      { id: "thattu", name: "Thattukada", kind: "thattukada", x: -20, z: -6 },
      { id: "hotel", name: "Lodge", kind: "hotel", x: 6, z: 18 },
    ],
  },
];

export function getDistrict(id) {
  return DISTRICTS.find((d) => d.id === id) || DISTRICTS[6];
}

export function roadsFor(d) {
  const nodes = [{ x: d.start.x, z: d.start.z }, ...d.places];
  const main = [...nodes].sort((a, b) => a.x - b.x).map((p) => [p.x, p.z]);
  const north = nodes.filter((p) => p.z > 28).sort((a, b) => a.z - b.z).map((p) => [p.x, p.z]);
  const south = nodes.filter((p) => p.z < -40).sort((a, b) => a.x - b.x).map((p) => [p.x, p.z]);
  const roads = [main];
  if (north.length >= 2) roads.push(north);
  if (south.length >= 2) roads.push(south);
  return roads;
}
